-- Hardening: prevent QR token replay (nonce reuse) at the database layer.
-- Safe to apply after 20260426_create_checkins.sql.

-- Tokens generated by scripts/security/qr_secure.py always include a nonce.
-- Use a partial unique index so existing rows with NULL nonce (if any) won't break.
create unique index if not exists checkins_token_nonce_uniq
  on public.checkins (token_nonce)
  where token_nonce is not null;

